### ISSUE TITLE
Failed test because of invalid pcre pattern

### ISSUE THREAD

**Issue by remicollet** [FriendsOfPHP/PHP-CS-Fixer#4405]
This only affects PHP 7.3 build with lilbpcre2 >= 10.33

In `NoSuperfluousElseifFixer::convertElseifToIf()` , the `/(\R[^\R]*)$/` pattern raise a 'Compilation failed' 

I suspect a change / regression in libpcre2, so have ping the package maintainer.

So, mostly FYI, will give more detail ASAP

=> https://bugzilla.redhat.com/show_bug.cgi?id=1706742
